services:
  api:
    image: thefuadeniola/blog-server
    environment:
      DATABASE_URL:  "mysql://actix_user:actixpass@db:3306/blog_server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: blog_server
      MYSQL_USER: actix_user
      MYSQL_PASSWORD: actixpass
      MYSQL_ROOT_PASSWORD: 123456

    ports:
      - "3306:3306"
    volumes:
      - ./sqltables:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql 

volumes:
  db:
    driver: local